//! The embedded payload, generated by `build.rs`.
//!
//! `PAYLOAD` is `(name written to the player, owning component id, bytes)`. `UNINSTALL_UPG` is
//! the removal package, kept apart from the table because it lands under the same name as the
//! install one. `MISSING` / `UPDATER_MISSING` list what was absent at compile time so an
//! incomplete build says so on startup instead of half-working.

// UPDATER_PAYLOAD is Windows-only; the table is generated unconditionally so both targets
// build from one generator.
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/payload.rs"));
