//! The embedded payload, generated by `build.rs`.
//!
//! `PAYLOAD` is `(name written to the player, owning component id, bytes)`. `UNINSTALL_UPG` is
//! the removal package, kept apart from the table because it lands under the same name as the
//! install one. `MISSING` lists what was absent at compile time so an
//! incomplete build says so on startup instead of half-working.

#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/payload.rs"));
