#!/usr/bin/env python3
"""Generate the harness's vtable slot map by READING main.cpp.

main.cpp calls Sony's service clients through raw slot indices — `bt_slot(c, 30)` — with a local
`enum { VIDX_AddListener = 30 };` next to each call site as the only record of what slot 30 is. The
harness needs the same map to name what the app reached for, and the first hand-written version of
that table got two entries backwards (AddListener is slot 30 on BtCommonServiceClient and 39 on
BtTransmitterServiceClient, not the other way round), which made a passing bring-up look like a
missing one.

So don't hand-write it. Each call site names both the object (`c`/`g_bt_common` = common,
`x`/`xg`/`g_bt_xmit` = transmitter) and the VIDX_ constant, and the enclosing enum gives the number.
If a slot index is ever corrected in main.cpp, this map follows it on the next harness run.
"""
import re, sys, pathlib, collections

SVC = {'c': 'BtCommon', 'g_bt_common': 'BtCommon',
       'x': 'BtXmit', 'xg': 'BtXmit', 'g_bt_xmit': 'BtXmit'}


def main():
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'cinder-home/src/main.cpp').read_text()

    # Every VIDX_ constant ever assigned, and every value it is assigned. A name used with two
    # different values in the two services (AddListener) shows up here as two entries, which is why
    # the call site — not this table — decides.
    values = collections.defaultdict(set)
    for m in re.finditer(r'(VIDX_[A-Za-z]+)\s*=\s*(\d+)', src):
        values[m.group(1)].add(int(m.group(2)))

    lines = src.split('\n')
    scope = {}          # VIDX name -> value, from the nearest preceding enum block
    found = {}          # (service, slot) -> method name
    conflicts = []
    for line in lines:
        for m in re.finditer(r'(VIDX_[A-Za-z]+)\s*=\s*(\d+)', line):
            scope[m.group(1)] = int(m.group(2))
        for m in re.finditer(r'bt_slot\(\s*([A-Za-z_0-9]+)\s*,\s*([^)]*?VIDX_[A-Za-z]+[^)]*)', line):
            svc = SVC.get(m.group(1))
            if not svc:
                continue
            for name in re.findall(r'VIDX_[A-Za-z]+', m.group(2)):
                slot = scope.get(name)
                if slot is None:
                    # A multi-line enum: fall back to the constant's only known value.
                    vals = values.get(name, set())
                    if len(vals) != 1:
                        continue
                    slot = next(iter(vals))
                method = name[len('VIDX_'):]
                prev = found.get((svc, slot))
                if prev and prev != method:
                    conflicts.append((svc, slot, prev, method))
                found[(svc, slot)] = method

    if conflicts:
        for svc, slot, a, b in conflicts:
            print(f"gen_slotmap: {svc} slot {slot} is both {a} and {b}", file=sys.stderr)
        return 1

    out = ['// GENERATED by cinder-home/harness/gen_slotmap.py from cinder-home/src/main.cpp.',
           '// Do not edit — the call sites in main.cpp are the source of truth for these numbers.',
           '#pragma once', '',
           'struct CinderSlotName { int slot; const char* name; };', '']
    for svc, var in (('BtCommon', 'kBtCommonSlots'), ('BtXmit', 'kBtXmitSlots')):
        rows = sorted((s, n) for (v, s), n in found.items() if v == svc)
        out.append(f'static const CinderSlotName {var}[] = {{')
        for slot, name in rows:
            out.append(f'    {{{slot:>3}, "{svc}::{name}"}},')
        out.append('    {  0, nullptr},')
        out.append('};')
        out.append('')
    # The UAC client's slots are not reached through bt_slot(), so they stay hand-written.
    out += ['static const CinderSlotName kUacSlots[] = {',
            '    {  3, "Uac::GetStatus"},',
            '    {  4, "Uac::Start"},',
            '    {  5, "Uac::Stop"},',
            '    {  6, "Uac::AddListener"},',
            '    {  0, nullptr},',
            '};', '']
    print('\n'.join(out))
    print(f'// {len(found)} slots mapped', file=sys.stderr)
    return 0


sys.exit(main())
