#!/usr/bin/env python3
"""Generate recording stubs for every C entry point main.cpp calls.

main.cpp is the unit under test in this harness; everything it calls is replaced by a stub that
RECORDS the call and returns a scriptable value. That is what makes the defect class this project
keeps hitting visible off-device: "was refresh_bt_paired called during boot", "how many times a
second is this called", "is SetSelectUsingEq ever called at all" are all questions about the call
TRACE, not about a return value.

Signatures come from the real headers, so a stub cannot drift from the thing it replaces — if a
header changes, this regenerates and the harness stops compiling until it is dealt with.
"""
import re, sys, pathlib

HEADERS = [
    "player/cinder-ffi/include/cinder.h",
    "cinder-audio/include/cinder_audio.h",
    "cinder-audio/include/cinder_effects.h",
    "cinder-audio/include/cinder_analyzer.h",
    "cinder-audio/include/cinder_power.h",
    "cinder-audio/include/cinder_tuner.h",
]

# `TYPE name(args);` on one line — that is how every one of these headers is written. The type
# alternatives are spelled out longest-first (and `unsigned` on its own is one of them) because the
# earlier shorter pattern silently skipped `unsigned cinder_audio_listener_events(void);` and four
# `int cinder_fm_*(void);` lines that carry a trailing /* comment */ — a missed declaration is not a
# generator warning, it is a link error in the harness, which is how those five were found.
DECL = re.compile(r'^\s*((?:const\s+)?'
                  r'(?:unsigned\s+long\s+long|unsigned\s+long|unsigned\s+int|unsigned\s+char'
                  r'|signed\s+char|unsigned|long\s+long|long|int|void|float|double|char|size_t)'
                  r'(?:\s*\*+)?)\s*\b([a-z_][a-z0-9_]*)\s*\(([^;]*)\)\s*;')

ZERO = {'void': None, 'float': '0.0f', 'double': '0.0'}

def default_return(rt):
    rt = rt.strip()
    if rt == 'void':
        return None
    if '*' in rt:
        return 'nullptr'
    if rt in ('float', 'double'):
        return ZERO[rt]
    return '0'

def root_rel(h):
    # stubs.cpp lives in cinder-home/harness/; the headers are named relative to the repo root.
    return '../../' + h


def main():
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')
    decls = []
    seen = set()
    for h in HEADERS:
        p = root / h
        if not p.exists():
            continue
        for line in p.read_text().split('\n'):
            m = DECL.match(line)
            if not m:
                continue
            rt, name, args = m.group(1).strip(), m.group(2), m.group(3).strip()
            if not name.startswith('cinder_') or name in seen:
                continue
            seen.add(name)
            decls.append((rt, name, args))

    out = ['// GENERATED by cinder-home/harness/gen_stubs.py — do not edit by hand.',
           '// Recording stubs for every C entry point main.cpp calls. See the generator for why.',
           '#include "harness.h"']
    # Include the real headers rather than re-declaring: a stub whose signature drifts from the
    # thing it replaces then fails to COMPILE instead of quietly mismatching at the ABI level.
    for h in HEADERS:
        out.append(f'#include "{root_rel(h)}"')
    out += ['', 'extern "C" {', '']
    for rt, name, args in sorted(decls, key=lambda d: d[1]):
        a = 'void' if args in ('', 'void') else args
        # Strip parameter names for the definition where they are unused, but keep the first int-ish
        # one so the trace can carry it — that is what makes "set_bt_on(0)" distinguishable from
        # "set_bt_on(1)" in an assertion.
        first_int = None
        if a != 'void':
            for part in a.split(','):
                part = part.strip()
                pm = re.match(r'^(?:const\s+)?(?:unsigned|signed)?\s*(?:int|long long|long|char)?\s+'
                              r'([a-z_][a-z0-9_]*)$', part)
                if pm:
                    first_int = pm.group(1)
                    break
        rv = default_return(rt)
        out.append(f'{rt} {name}({a}) {{')
        if first_int:
            out.append(f'    cinder_harness_record("{name}", (long long){first_int});')
        else:
            out.append(f'    cinder_harness_record("{name}", 0);')
        out.append(f'    long long scripted = 0;')
        out.append(f'    if (cinder_harness_scripted("{name}", &scripted)) '
                   f'return {"" if rv is None else f"({rt})scripted"};')
        if rv is not None:
            out.append(f'    return {rv};')
        out.append('}')
        out.append('')
    out += ['} // extern "C"']
    print('\n'.join(out))
    print(f'// {len(decls)} stubs generated', file=sys.stderr)

main()
