// build.rs — embed the staged payload into the installer binary.
//
// The installer ships as ONE file from a GitHub release, so everything it needs to write to the
// player has to live inside it: the device binaries, the install/uninstall .UPGs, and the
// component catalogue (embedded rather than duplicated, so deploy/components.conf stays the single
// source of truth for what is optional).
//
// Which channel is embedded is chosen at BUILD time:  CINDER_CHANNEL=dev cargo build …
//
// A MISSING payload is not a build error. It emits an empty table, the installer starts, reports
// exactly which files are absent and exits non-zero. That keeps `cargo build` and `cargo check`
// working in a fresh clone or in CI before cinder-home/build.sh has ever run — the alternative
// (include_bytes! on a missing path) fails with a compiler error that says nothing useful.
use std::path::{Path, PathBuf};
use std::{env, fs};

// (source path, name written to the player's storage root, owning component id, required?)
//
// The component id ties a file to a catalogue entry, so the installer stages only what was
// actually selected — an empty id means "always". `required: false` is for files that legitimately
// exist on one channel only (cinder-gpunode is dev-channel only), so a stable build does not
// report them as missing.
const FILES: &[(&str, &str, &str, bool)] = &[
    ("dist/{ch}/cinder-home", "cinder-home", "", true),
    ("dist/{ch}/cinder-probe", "cinder-probe", "", true),
    // Empty id = always staged. These four were catalogue components until 2026-09-12, when the
    // four "choices" that removed the power menu, file transfer, the clock and the unmount helper
    // were taken out of deploy/components.conf: each one's own description said the feature was
    // gone without it. They are part of every install now, and 60 KB between them.
    ("dist/{ch}/cinder-umount", "cinder-umount", "", true),
    ("dist/{ch}/cinder-power", "cinder-power", "", true),
    ("dist/{ch}/cinder-msc", "cinder-msc", "", true),
    ("dist/{ch}/cinder-clock", "cinder-clock", "", true),
    // Built on both channels, so `required` — a stable build missing either is a real defect, not
    // a channel difference. cinder-fm backs the FM signal meter / fast scan / hardware seek;
    // cinder-voltable installs the chosen output volume table on every boot.
    ("dist/{ch}/cinder-fm", "cinder-fm", "fm", true),
    // Empty id = always staged, same as cinder-signature.sh: `voltable` is an ENUM component
    // (stock/wm1a/w1), so there is no "off" that should skip the helper — the curve can be changed
    // on-device later by editing /contents/cinder_voltable.conf, and that needs the binary present.
    ("dist/{ch}/cinder-voltable", "cinder-voltable", "", true),
    // cinder-battery READS the bq24262 charger's registers for the battery screen. Deliberately
    // read-only — unlike cinder-fm it never widens permissions, because writing this chip
    // reprograms a lithium charger. See cinder-home/src/cinder-battery.c.
    ("dist/{ch}/cinder-battery", "cinder-battery", "battery", true),
    ("dist/{ch}/cinder-gpunode", "cinder-gpunode", "gpunode", false),
    ("dist/{ch}/cinder-signature.sh", "cinder-signature.sh", "", true),
    // The .UPG the Sony updater actually runs. It MUST land on the player as NW_WM_FW.UPG —
    // that filename is what the device's own "update firmware" flow looks for.
    ("dist/{ch}/cinder_home_install.upg", "NW_WM_FW.UPG", "", true),
];

// The uninstall package. Deliberately NOT in FILES: it lands under the same name as the install
// one, so staging both would mean writing NW_WM_FW.UPG twice and letting file order decide what
// the player flashes. It is emitted as its own constant and written only by the uninstall action.
//
// It was previously not embedded at all, which is why removing Cinder meant reading UNINSTALL.md
// and copying a file by hand — the uninstall .UPG was built, committed and published as a release
// asset the whole time, and the one program the user actually runs could not reach it.
const UNINSTALL_UPG: &str = "dist/{ch}/cinder_home_uninstall.upg";

fn main() {
    embed_manifest();
    let channel = env::var("CINDER_CHANNEL").unwrap_or_else(|_| "stable".into());
    println!("cargo:rerun-if-env-changed=CINDER_CHANNEL");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ch_root = manifest.parent().unwrap().join("cinder-home");
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut src = String::new();
    src.push_str("// generated by build.rs — do not edit\n");
    src.push_str(&format!("pub const CHANNEL: &str = {:?};\n", channel));

    // the component catalogue, embedded so the picker and the device installer agree
    let cat = ch_root.join("deploy/components.conf");
    println!("cargo:rerun-if-changed={}", cat.display());
    match fs::read(&cat) {
        Ok(b) => src.push_str(&format!(
            "pub const CATALOGUE: Option<&str> = Some({:?});\n",
            String::from_utf8_lossy(&b)
        )),
        Err(_) => src.push_str("pub const CATALOGUE: Option<&str> = None;\n"),
    }

    let mut entries = Vec::new();
    let mut missing = Vec::new();
    for (rel, dest, owner, required) in FILES {
        let rel = rel.replace("{ch}", &channel);
        let p = ch_root.join(&rel);
        println!("cargo:rerun-if-changed={}", p.display());
        if p.is_file() {
            entries.push(format!(
                "    ({:?}, {:?}, include_bytes!({:?})),",
                dest,
                owner,
                abs(&p)
            ));
        } else if *required {
            missing.push(rel);
        }
    }

    src.push_str("pub static PAYLOAD: &[(&str, &str, &[u8])] = &[\n");
    for e in &entries {
        src.push_str(e);
        src.push('\n');
    }
    src.push_str("];\n");

    // the uninstall package, as its own optional constant
    {
        let rel = UNINSTALL_UPG.replace("{ch}", &channel);
        let p = ch_root.join(&rel);
        println!("cargo:rerun-if-changed={}", p.display());
        if p.is_file() {
            src.push_str(&format!(
                "pub static UNINSTALL_UPG: Option<&[u8]> = Some(include_bytes!({:?}));\n",
                abs(&p)
            ));
        } else {
            src.push_str("pub static UNINSTALL_UPG: Option<&[u8]> = None;\n");
            missing.push(rel);
        }
    }

    src.push_str("pub static MISSING: &[&str] = &[\n");
    for m in &missing {
        src.push_str(&format!("    {:?},\n", m));
    }
    src.push_str("];\n");

    // NO SONY UPDATER HERE, deliberately. Until 0.3.1 this embedded Sony's
    // SoftwareUpdateTool.exe, WmFwUpdater.dll and the Visual C++ 2010 runtime into every Windows
    // installer, for one thing: the 12-byte vendor SCSI command that reboots the player into its
    // updater. installer/src/stage.rs now sends that command itself on Windows (SCSI pass-through)
    // as it already did on Linux (SG_IO), so no part of Sony's software ships in this binary.

    if !missing.is_empty() {
        println!(
            "cargo:warning=cinder-installer: {} payload file(s) missing for channel '{}' — \
             run cinder-home/build.sh {} && cinder-home/tools/pack_upg.sh {} first",
            missing.len(),
            channel,
            channel,
            channel
        );
    }

    fs::write(out.join("payload.rs"), src).unwrap();
}

/// Ask the MSVC linker to embed the application manifest.
///
/// Without it the GUI paints in the Windows 95 control style — see the manifest's own comment.
/// Only the MSVC toolchain can do this from the linker alone; the GNU one needs `windres` to
/// compile a resource script, which is a build tool this project does not require anyone to have.
/// The GNU target is used for local `cargo check` only — every published Windows build is MSVC —
/// so a check-only build losing its theming costs nothing.
fn embed_manifest() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("cinder-installer.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    if env::var("CARGO_CFG_TARGET_ENV").as_deref() != Ok("msvc") {
        // The GNU toolchain has no linker switch for this, but it ships `windres`, which compiles
        // a resource script into a COFF object the linker will take like any other input. Worth
        // doing rather than skipping: a locally cross-built .exe is how the GUI actually gets
        // looked at before a release, and an unthemed one invites a bug report about the styling
        // instead of about the program.
        if !manifest.is_file() {
            return;
        }
        gnu_manifest(&manifest);
        return;
    }
    // A MISSING manifest must not fail the link. `/MANIFESTINPUT:` naming a file that is not
    // there is a hard linker error, so an unguarded pass would turn "the manifest was not
    // committed" into a broken release build whose message points at the linker rather than at
    // the file. Unthemed controls are a cosmetic loss; a failed release build is not.
    if !manifest.is_file() {
        println!("cargo:warning=cinder-installer: {} is missing — building without an application \
                  manifest, so the GUI will use unthemed controls.", manifest.display());
        return;
    }
    println!("cargo:rustc-link-arg-bins=/MANIFEST:EMBED");
    println!("cargo:rustc-link-arg-bins=/MANIFESTINPUT:{}", manifest.display());
    println!("cargo:rustc-link-arg-bins=/MANIFESTUAC:NO");
}

/// Compile the manifest into a COFF object with `windres` and hand it to the linker.
///
/// Best-effort by design: if `windres` is not installed the build continues without a manifest
/// (unthemed controls, everything else identical) rather than failing. Published builds are MSVC
/// and take the linker path above, so this never gates a release.
fn gnu_manifest(manifest: &Path) {
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let rc = out.join("manifest.rc");
    let obj = out.join("manifest_res.o");

    // 1 = CREATEPROCESS_MANIFEST_RESOURCE_ID, 24 = RT_MANIFEST. Forward slashes: windres reads
    // the path out of the script, where a backslash is an escape.
    let script = format!("1 24 \"{}\"\n", abs(manifest));
    if fs::write(&rc, script).is_err() {
        return;
    }

    for tool in ["x86_64-w64-mingw32-windres", "windres"] {
        let ok = std::process::Command::new(tool)
            .args(["-O", "coff", "-i"])
            .arg(&rc)
            .arg("-o")
            .arg(&obj)
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if ok {
            println!("cargo:rustc-link-arg-bins={}", obj.display());
            return;
        }
    }
    println!("cargo:warning=cinder-installer: windres not found — the GUI will use unthemed \
              controls in this build. Published builds are MSVC and are unaffected.");
}

fn abs(p: &Path) -> String {
    fs::canonicalize(p)
        .unwrap_or_else(|_| p.to_path_buf())
        .to_string_lossy()
        .replace('\\', "/")
}
