// build.rs — embed the staged payload into the installer binary.
//
// The installer ships as ONE file from a GitHub release, so everything it needs to write to the
// player has to live inside it: the device binaries, the install/uninstall .UPGs, and the
// component catalogue (embedded rather than duplicated, so deploy/components.conf stays the single
// source of truth for what is optional).
//
// Which channel is embedded is chosen at BUILD time:  CINDER_CHANNEL=dev cargo build …
//
// A MISSING payload is not a build error. It emits an empty table, the installer starts, reports
// exactly which files are absent and exits non-zero. That keeps `cargo build` and `cargo check`
// working in a fresh clone or in CI before cinder-home/build.sh has ever run — the alternative
// (include_bytes! on a missing path) fails with a compiler error that says nothing useful.
use std::path::{Path, PathBuf};
use std::{env, fs};

// (source path, name written to the player's storage root, owning component id, required?)
//
// The component id ties a file to a catalogue entry, so the installer stages only what was
// actually selected — an empty id means "always". `required: false` is for files that legitimately
// exist on one channel only (cinder-gpunode is dev-channel only), so a stable build does not
// report them as missing.
const FILES: &[(&str, &str, &str, bool)] = &[
    ("dist/{ch}/cinder-home", "cinder-home", "", true),
    ("dist/{ch}/cinder-probe", "cinder-probe", "", true),
    ("dist/{ch}/cinder-umount", "cinder-umount", "umount", true),
    ("dist/{ch}/cinder-power", "cinder-power", "power", true),
    ("dist/{ch}/cinder-msc", "cinder-msc", "msc", true),
    ("dist/{ch}/cinder-clock", "cinder-clock", "clock", true),
    ("dist/{ch}/cinder-gpunode", "cinder-gpunode", "gpunode", false),
    ("dist/{ch}/cinder-signature.sh", "cinder-signature.sh", "", true),
    // The .UPG the Sony updater actually runs. It MUST land on the player as NW_WM_FW.UPG —
    // that filename is what the device's own "update firmware" flow looks for.
    ("dist/{ch}/cinder_home_install.upg", "NW_WM_FW.UPG", "", true),
];

fn main() {
    let channel = env::var("CINDER_CHANNEL").unwrap_or_else(|_| "stable".into());
    println!("cargo:rerun-if-env-changed=CINDER_CHANNEL");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ch_root = manifest.parent().unwrap().join("cinder-home");
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut src = String::new();
    src.push_str("// generated by build.rs — do not edit\n");
    src.push_str(&format!("pub const CHANNEL: &str = {:?};\n", channel));

    // the component catalogue, embedded so the picker and the device installer agree
    let cat = ch_root.join("deploy/components.conf");
    println!("cargo:rerun-if-changed={}", cat.display());
    match fs::read(&cat) {
        Ok(b) => src.push_str(&format!(
            "pub const CATALOGUE: Option<&str> = Some({:?});\n",
            String::from_utf8_lossy(&b)
        )),
        Err(_) => src.push_str("pub const CATALOGUE: Option<&str> = None;\n"),
    }

    let mut entries = Vec::new();
    let mut missing = Vec::new();
    for (rel, dest, owner, required) in FILES {
        let rel = rel.replace("{ch}", &channel);
        let p = ch_root.join(&rel);
        println!("cargo:rerun-if-changed={}", p.display());
        if p.is_file() {
            entries.push(format!(
                "    ({:?}, {:?}, include_bytes!({:?})),",
                dest,
                owner,
                abs(&p)
            ));
        } else if *required {
            missing.push(rel);
        }
    }

    src.push_str("pub static PAYLOAD: &[(&str, &str, &[u8])] = &[\n");
    for e in &entries {
        src.push_str(e);
        src.push('\n');
    }
    src.push_str("];\n");

    src.push_str("pub static MISSING: &[&str] = &[\n");
    for m in &missing {
        src.push_str(&format!("    {:?},\n", m));
    }
    src.push_str("];\n");

    if !missing.is_empty() {
        println!(
            "cargo:warning=cinder-installer: {} payload file(s) missing for channel '{}' — \
             run cinder-home/build.sh {} && cinder-home/tools/pack_upg.sh {} first",
            missing.len(),
            channel,
            channel,
            channel
        );
    }

    fs::write(out.join("payload.rs"), src).unwrap();
}

fn abs(p: &Path) -> String {
    fs::canonicalize(p)
        .unwrap_or_else(|_| p.to_path_buf())
        .to_string_lossy()
        .replace('\\', "/")
}
